jadewisemann/EST_FE--4th__TEAM--2nd__3rd-

- src/components/Icon.jsx
> feat: add icon

- package.json
- src/components/Icon.jsx
> feat: add icon sort

- src/components/Icon.jsx
> feat: modify icon component

- src/components/Rating.jsx
- src/components/ReviewRating.jsx
> feat: add rating

- src/components/Icon.jsx
> fix: modify icon component

- src/components/Rating.jsx
- src/components/ReviewRating.jsx
> fix : modify rating

- src/components/Radio.jsx
- src/pages/@test/index.jsx
> feat: add radio

- src/components/Radio.jsx
> fix: radio button 컴포넌트명 수정

- src/components/CheckBox.jsx
- src/pages/@test/index.jsx
> feature: add check box

- src/components/HorizontalList.jsx
> fix: add img round

- src/components/HorizontalList.jsx
> fix: modify heart position

- src/components/Icon.jsx
- src/pages/@test/index.jsx
> fix: modify icon naming

- src/App.css
- src/App.jsx
- src/components/DetailProduct.jsx
- src/components/HorizontalList.jsx
- src/pages/details/index.jsx
datail page 추가
App.jsx - swiper.css 추가
App.css - swiper pagination 관련 css 추가 , container 관련 css 추가
> feat: add details page

- src/components/Nav.jsx
네비바가 기본으로 보이도록 수정,
경로가 변경될 때 메뉴의 액티브가 변경되지않는 부분을 activeNavMenu로 관리
> fix: add activeNavMenu update

- src/components/CheckBox.jsx
fix : add className params checkbox component
> fix : add className params checkbox component

- src/App.jsx
- src/pages/checkout/index.jsx
- src/pages/index.jsx
> feat : add checkout page

- src/pages/wishlist/index.jsx
> feat: add wishlist page

- src/App.css
- src/App.jsx
- src/pages/index.jsx
- src/pages/reservation-detail/index.jsx
feat: add reservation detail page
> feat: add reservation detail page

- src/pages/checkout/index.jsx
fix: delete unused code, modify className
> fix: delete unused code, modify className

- src/pages/details/index.jsx
fix: change line, modify style
> fix: change line, modify style

- src/components/HorizontalList.jsx
> fix: image size fixed

- src/components/Radio.jsx
fix : add radio onchange event
> fix : add radio onchange event

- src/components/CheckBox.jsx
> fix : add onchange event

- index.html
- src/App.jsx
- src/components/DetailProduct.jsx
- src/pages/details/components/ShareBtn.jsx
- src/pages/details/index.jsx
fix : detail page add data
detail page apply data 
add kakao share btn feat
modify router
> fix : detail page add data

- src/pages/checkout/index.jsx
> fix: checkout page apply data

- src/pages/details/components/ShareBtn.jsx
- src/pages/details/index.jsx
fix: detail page delete console data, apply userdata
> fix: detail page delete console data, apply userdata

- src/pages/checkout/index.jsx
- src/pages/details/index.jsx
fix: detail page, checkout page header add zindex
> fix: detail page, checkout page header add zindex

- src/App.css
- src/App.jsx
- src/components/DetailProduct.jsx
- src/components/Rating.jsx
- src/pages/details/components/ShareBtn.jsx
- src/pages/details/index.jsx
fix: detail page change data, modify components
> fix: detail page change data, modify components

- src/App.css
- src/components/Anchor.jsx
- src/components/HorizontalList.jsx
- src/pages/wishlist/index.jsx
> feature: wishlist apply data

- src/pages/order-confirm/index.jsx
feature: order-confirm apply data
> feature: order-confirm apply data

- src/components/Icon.jsx
- src/components/Input.jsx
fix: change tel input icon, add phone icon
> fix: change tel input icon, add phone icon

- src/App.css
- src/pages/main/index.jsx
- src/store/darkModeStore.js
> feature/ add dark mode

- src/App.css
- src/components/CheckBox.jsx
- src/components/HorizontalList.jsx
- src/components/Radio.jsx
- src/components/Rating.jsx
- src/pages/@test/index.jsx
- src/pages/checkout/index.jsx
- src/pages/details/components/DetailProduct.jsx
- src/pages/details/index.jsx
> feat: add dark mode (han)

- src/App.jsx
- src/pages/checkout/index.jsx
> feat: checkout page apply payment

- src/pages/details/index.jsx
> loading 추가 및 여백 수정

- src/pages/checkout/index.jsx
- src/pages/reservation-detail/index.jsx
feat: apply data reservation detail page
> feat: apply data reservation detail page

- src/pages/checkout/index.jsx
- src/pages/reservation-detail/index.jsx
> fix: add payment loading
